set guifont=JetBrainsMono\ Nerd\ Font:h15
colorscheme one
if has("gui_macvim")
  set macmeta
  map <M-C-S-D-F19> <Nop>
  map! <M-C-S-D-F19> <Nop>
  map <S-F15> <Nop>
  map! <S-F15> <Nop>
endif

if exists("g:neovide")
  set guifont=JetBrainsMono\ Nerd\ Font,Sarasa\ Mono\ K:h15

  " https://github.com/neovide/neovide/issues/113
  " https://github.com/neovide/neovide/issues/1263
  " system clipboard
  let g:neovide_input_use_logo = 1
  vmap     <D-c> "+y
  map      <D-v> "+p
  noremap! <D-v> <C-R>+

  " insert original character without triggering things like auto-pairs
  imap <C-r> <D-v>
endif
