#!/usr/bin/env bash
# cobra_complete docker
# Fall back to bash completion until https://github.com/docker/cli/issues/4932 is resolved.
if [ -n "$BASH" ]; then
  : # noop
elif [ -n "$ZSH_NAME" ]; then
  ZSH_BASH_COMPLETIONS_FALLBACK_WHITELIST+=(docker)
fi
# TIP: Read to the completion script for more options.
target=bash staticfile_complete '' /Applications/Docker.app/Contents/Resources/etc/docker.bash-completion docker
alias d=docker