#!/usr/bin/env bash

# Logi Options+ app brings a weird side effect: it changes the "Swipe between pages" option to "off".
# This script sets the "Swipe between pages" option back to "Swipe with two or three fingers".

# Register this script to crontab!

current_value=$(defaults read NSGlobalDomain AppleEnableSwipeNavigateWithScrolls 2>/dev/null)
if [ "$current_value" != "1" ]; then
    defaults write NSGlobalDomain AppleEnableSwipeNavigateWithScrolls -bool true
    /System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u
fi
