#!/usr/bin/env bash

awsp() {
  case "$1" in
    -h|--help)
      cat <<EOF
Usage: awsp [profile]
  Print the current profile if no argument is given.
  Switch to the specified profile if an argument is given.
EOF
      return
      ;;
  esac
  if [ -z "${1:-}" ]; then
    echo "${AWS_PROFILE:-<unset>}"
    return
  fi
  export AWS_PROFILE="$1"
}

_fzf_complete_awsp() {
  stdin_fzf_completer profile 2 "$@" \
    < <(env -i PATH="$PATH" COMP_LINE='aws --profile ' COMP_POINT=14 aws_completer)
}

staticfile_complete awscmds "$DOTFILES/aws/completion.bash" awsp