#!/usr/bin/env bash
awsp() {
  export AWS_PROFILE="$1"
}

_fzf_complete_awsp() {
  stdin_fzf_completer profile 2 "$@" \
    < <(env -i PATH="$PATH" COMP_LINE='aws --profile ' COMP_POINT=14 aws_completer)
}

staticfile_complete awscmds "$DOTFILES/aws/completion.bash" awsp