tap "homebrew/bundle"
tap "homebrew/services"

# [macos]: macOS has own versions
# [gnu]: GNU dialect

# Interactive
brew "bash" # [macos]
brew "bash-completion@2"
brew "zsh" # [macos]
brew "tmux"
brew "zoxide"
brew "tree"
brew "pstree"
brew "neovim"
brew "less" # [macos]
brew "mandoc" # [macos]
brew "man-db" # [macos]
brew "ncurses" # [macos,keg-only]
brew "fd"
brew "yazi"

# Searching
brew "ack"
brew "fzf"
brew "grep" # [macos]
brew "ripgrep"

# Viewing
brew "bat"

# Data inspection/processing/formatting
brew "awk" # [macos] nawk
brew "gawk" # [macos] g-prefixed
brew "gnu-sed" # [macos] g-prefixed
brew "jq"
brew "jless"
brew "yq"
brew "groff"
brew "yamlfmt"

# Network clients
brew "bind" # [macos]
brew "nmap"
brew "curl" # [macos,keg-only]
brew "wget"
brew "websocat"
brew "rsync"

# Security tools
brew "gnupg"
brew "krb5" # [macos,keg-only]

# Devtools
brew "make" # [macos]
brew "gh"
brew "git" # [macos]
brew "git-delete-merged-branches"
brew "git-delta"
brew "git-lfs"
cask "git-credential-manager"
tap "jesseduffield/lazygit"
brew "jesseduffield/lazygit/lazygit"
brew "helm"
brew "tilt"
brew "fnm"
brew "awscli"
brew "docker-credential-helper-ecr"
brew "pyenv"

# Language tools
brew "ruby"
brew "shellcheck"
brew "shfmt"

# Etc
brew "gnu-tar" # [macos] g-prefixed
brew "expect" # [macos]
brew "coreutils" # [macos] g-prefixed
brew "diffutils" # [macos] g-prefixed
brew "findutils" # [macos] g-prefixed
brew "pipx"
brew "unar"
brew "rename"
brew "imagemagick"
brew "direnv"


# Fonts
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
