#!/usr/bin/env bash
osc() {
  local k
  for k in $(awk 'BEGIN{for(v in ENVIRON) print v}' | grep '^OS_'); do
    eval "export ${k}="
  done
  export OS_CLOUD="$1"
}

osce() {
  local clouds_path=~/.config/openstack/clouds.yaml
  local secure_path=~/.config/openstack/secure.yaml
  # TODO: extract ~/.dotfiles to a variable DOTFILES
  local configconv=~/.dotfiles/openstack/configconv
  local cloud_name="$1"

  local IFS=$'\n'
  local envs=( $(cat <(<"$clouds_path" "$configconv" "$cloud_name") <(<"$secure_path" "$configconv" "$cloud_name")) )
  local env
  for env in "${envs[@]}"; do
    export "$env"
  done
  export OS_CLOUD=
  # export OS_CLOUD_NAME="$cloud_name"
}

ostok() {
  local token
  token=$(openstack token issue -c id -f value)
  export OS_TOKEN="$token" AUTH_TOKEN="$token"
  if [ "$1" = copy ]; then
    pbcopy <<< "$token"
  fi
}