#!/usr/bin/env bash
set -eu

source "$DOTFILES/util.bash"
SCRIPT_DIR="$(script_dir)"

ohai bash:installconf
for f in bash_logout bash_profile bashrc; do
  symlink_safe "$SCRIPT_DIR/$f" ~/".$f"
done

gen() {
  echo '# Generated by dotfiles'
  sed "s|:PH_DOTFILES:|${DOTFILES}|g" <"$SCRIPT_DIR/$1"
}

for f in bash_completion bashenv; do
  if ! grep -q '^# Generated by dotfiles' ~/".$f"; then
    gen "$f" | write_safe ~/".$f"
  elif [[ ~/.bashenv -ot "$SCRIPT_DIR/bashenv" ]]; then
    gen "$f" >~/".$f"
  fi
done
