if [ "${BASH_VERSINFO[0]}" -lt 5 ]; then
  >&2 echo "WARNING: You are running the version less than 5. The startup scripts might result in unexpected behavior."
fi

# This file gets run in two cases:
# 1. non-login interactive shell
# 2. remote shell (over ssh or similar)

# #2 happens when you run "ssh user@host bash" explicitly.
# in this case, /etc/bash.bashrc has not been previous executed (unlike #1).
# however, we assume that #2 is a recovery mode, so we don't want to do much.
# (also, my google-fu didn't find a way to distinguish them)

# shellcheck disable=SC1090
source ~/.bashenv
[[ $- == *i* ]] && source "$DOTFILES/bash/interactive"

# Reference: https://heptapod.host/flowblok/shell-startup/-/blob/branch/default/.bashrc
