if [ "${BASH_VERSINFO[0]}" -lt 5 ]; then
  >&2 echo "WARNING: You are running the version less than 5. The startup scripts might result in unexpected behavior."
fi

# Ensure 'shenv' gets run first
# The second dummy argument is required to source in login shells.

# shellcheck disable=SC1090
source ~/.bashenv -

# Run 'login'
source "$DOTFILES/bash/profile"

# Run 'interactive' if this is an interactive shell.
[[ $- == *i* ]] && source "$DOTFILES/bash/interactive"

# Reference: https://heptapod.host/flowblok/shell-startup/-/blob/branch/default/.bash_profile
