if [ "${BASH_VERSINFO[0]}" -lt 5 ]; then
  >&2 echo "WARNING: You are running the version less than 5. The startup scripts might result in unexpected behavior."
fi

_iife() {

local DOTFILES=:PH_DOTFILES:

# Ensure 'shenv' gets run first
# The second argument is required to source in login shells.
source "$DOTFILES/bash/shenv" .

# Run 'login'
source "$DOTFILES/bash/login"

# Run 'interactive' if this is an interactive shell.
[[ $- == *i* ]] && source "$DOTFILES/bash/interactive"

# Reference: https://heptapod.host/flowblok/shell-startup/-/blob/branch/default/.bash_profile

} && _iife
unset _iife
