#!/usr/bin/env bash

# Some ${...} texts in single quotes are intentional.
#shellcheck disable=SC2016

colors16() {
  for x in {0..8}; do
    for i in {30..37} {90..97}; do
      echo -ne "\e[$x;$i""m\\\e[$x;$i""m\e[0m "
      for a in {40..47} {100..107}; do
        echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0m "
      done
      echo
    done
  done
  echo
}

colors256() {
    echo -en "\n   +  "
    for i in {0..35}; do
        printf "%2b " "$i"
    done
    printf "\n\n %3b  " 0
    for i in {0..15}; do
        echo -en "\033[48;5;${i}m  \033[m "
    done
    #for i in 16 52 88 124 160 196 232; do
    for i in {0..6}; do
        let "i = i*36 +16"
        printf "\n\n %3b  " $i
        for j in {0..35}; do
            let "val = i+j"
            echo -en "\033[48;5;${val}m  \033[m "
        done
    done
    echo -e "\n"
}