#!/usr/bin/env bash

# ignorespace: lines which begin with a space (0x20) are not saved
# ignoredups: lines matching the previous entry are not saved
HISTCONTROL=ignorespace:ignoredups
HISTSIZE=10000
HISTTIMEFORMAT='%F %T '
# TODO: HISTFILE=<reasonable terminal session identifier>
HISTFILESIZE=10000
# The history list is appended to the file named by the vaue of the
# $HISTFILE Wwhen the shell exits, rather than overwriting the file
shopt -s histappend

# Checks the window size after each non-builtin command, and
# if necessary, updates the values of $LINES and $COLUMNS
shopt -s checkwinsize

# ** : matches all files and 0+ [sub]directories
# **/: matches 0+ [sub]directories
# '**' is only mearingful in pathname expansion context
shopt -s globstar

shopt -s autocd cdspell

# Why is this not the default?
shopt -u sourcepath

# `cd foo` may be assumed to be `cd $foo`
shopt -s cdable_vars

alias() {
  local ret=0 r
  for arg in "$@"; do
    builtin alias "$arg"; r=$?
    if [[ $r -ne 0 ]]; then
      ret=$r
    fi
    if [[ $arg != [^-=]*=?* ]]; then
      continue
    fi
    complete -F _complete_alias "${arg%%=*}"
  done
  return $ret
}


# bash-completion@2 {{{
# shellcheck disable=SC1091,SC2034
repair_builtin_completions() {
  local comp_src_dir="$HOMEBREW_PREFIX/etc/bash_completion.d"
  local comp_dest_dir="$HOME/.local/share/bash-completion-sys/completions"

  if [[ $comp_dest_dir -nt $comp_src_dir ]]; then
    return
  fi

  local name_skip_list=(
    '000_bash_completion_compat.bash'
    brew
    brew-services
    git-prompt.sh
    python-argcomplete
  )
  local name_rename_list=(
    aws aws_bash_completer
    git git-completion.bash
    hub hub.bash_completion.sh
    ninja ninja-completion.sh
  )
  if [ -e "$comp_dest_dir" ]; then
    rm -rf "$comp_dest_dir"
  fi
  mkdir -p "$comp_dest_dir"

  local f 
  for f in "$comp_src_dir"/*; do
    name="${f##*/}"

    for skip in "${name_skip_list[@]}"; do
      if [[ "$name" == "$skip" ]]; then
        continue 2
      fi
    done

    for ((i = 0; i < ${#name_rename_list[@]}; i += 2)); do
      cmd="${name_rename_list[i]}"
      match="${name_rename_list[i + 1]}"
      if [[ "$name" == "$match" ]]; then
        name="$cmd"
        break
      fi
    done

    ln -sf "$f" "$comp_dest_dir/$name"
  done

  cat >"$comp_dest_dir/brew" <<EOF
source "$comp_src_dir/brew"
source "$comp_src_dir/brew-services"
EOF
}
# shellcheck disable=SC2034
{
  # https://github.com/orgs/Homebrew/discussions/4202#discussioncomment-8636880
  repair_builtin_completions; unset -f repair_builtin_completions
  BASH_COMPLETION_COMPAT_DIR=/dev/null
  BASH_COMPLETION_USER_DIR="$HOME/.local/share/bash-completion:$HOME/.local/share/bash-completion-sys"
  [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]] && . "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  [[ -r "${HOMEBREW_PREFIX}/etc/bash_completion.d/000_bash_completion_compat.bash" ]] && . "${HOMEBREW_PREFIX}/etc/bash_completion.d/000_bash_completion_compat.bash"
}
# }}}
li=(
  zoxide
  docker
  kubernetes
  terraform
  openstack
  aws
  macos
  git
  fzf
  local
)
for b in "${li[@]}"; do
  # shellcheck disable=SC1090
  source "$DOTFILES/$b/shcmd"
done; unset li

source "$DOTFILES/terminal/iterm2/shell_integration.bash"

# source "$DOTFILES/bash/color"
source "$DOTFILES/shell/interactive"
source "$DOTFILES/bash/prompt"

eval "$(direnv hook bash)"
