#!/usr/bin/env bash

# Prevent login non-interactive shells from sourcing it again.
if shopt -q login_shell && [ -z "${1-}" ]; then
  return
fi

if [ "${BASH_VERSINFO[0]}" -lt 5 ]; then
  >&2 echo "WARNING: You are running the version less than 5. The startup scripts might result in unexpected behavior." >&2
fi

# We need to set $ENV so that if you use shell X as your login shell,
# and then start "sh" as a non-login interactive shell the startup scripts will
# correctly run.
# https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html
export ENV="$DOTFILES/bash/interactive"

# We also need to set BASH_ENV, which is run for *non-interactive* shells.
# (unlike $ENV, which is for interactive shells)
export BASH_ENV="$DOTFILES/bash/shenv"

# Only interactive shells are qualified to set $SHELL_SESSION_ID
if [[ $- == *i* ]]; then
  declare -xgr SHELL_SESSION_ID="$EPOCHSECONDS-$$-$BASH_SUBSHELL-$BASHPID"
fi

umask 0077

test -r "$DOTFILES/bash/shenv__local" && source "$DOTFILES/bash/shenv__local"

# Reference: https://heptapod.host/flowblok/shell-startup/-/blob/branch/default/.shell/env
